# Change to 0,0 on release !
SCREEN_RES_X = 1440
SCREEN_RES_Y = 900
TOP_MENU_HEIGHT = 80
STATUS_BAR_HEIGHT = 40
LEFT_MENU_WIDTH = 500
MENU_MARGIN = 50
LEFT_MENU_BUTTON_HEIGHT = 120
FONT_NAME = "Digital_tech.otf"
FONT_SIZE = 60

ALIGN_LEFT = 0
ALIGN_CENTER = 1
ALIGN_RIGHT = 2